# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'remoteColor' do
pod 'PocketSocket'
pod 'MMWormhole', '~> 1.1.1'

end

target 'remoteColorTests' do

end

